---
- hosts: all
  tasks:
  - name: Install system dependencies
    apt:
      name:
        - libcurl4-openssl-dev
        - libssl-dev
        - git
    become: true

  - name: Install pacman for R
    command: R -e 'install.packages("pacman");library(pacman);'

  - name: Install R dependencies
    command: >
      R -e 'pacman::p_load(Rserve, ellipse, scatterplot3d, Cairo, randomForest,
      caTools, e1071, som, impute, pcaMethods, RJSONIO, ROCR, globaltest, GlobalAncova,
      Rgraphviz, preprocessCore, genefilter, pheatmap, SSPA, sva, Rcpp, pROC, data.table,
      limma, car, fitdistrplus, lars, Hmisc, magrittr, methods, xtable, pls, caret, lattice,
      igraph, gplots, KEGGgraph, reshape, RColorBrewer, tibble, siggenes, plotly)'

  - name: Install MetaboAnalystR library
    command: >-
      R -e 'install.packages("devtools"); library(devtools);
      devtools::install_github("xia-lab/MetaboAnalystR")'
