---
- hosts: all
  tasks:

  - name: Install system dependencies
    apt:
      name:
        - libcurl4-openssl-dev
        - libssl-dev
        - libxml2-dev
      update_cache: true
    become: true

  - name: Remove bad version of libglib
    command: dpkg -r --force-all libglib2.0-0
    become: true

  - name: Fix packages
    command: apt install -f -y
    become: true

  - name: Install libglib dependent libraries
    apt:
      name:
        - libglib2.0-0
        - libglib2.0-dev
        - libcairo2-dev
        - libxt-dev
    become: true

  - name: Install R dependencies
    command: R -e 'install.packages("{{ item }}")'
    with_items:
      - 'XML'
      - 'plotly'
      - 'BiocManager'

  - name: Install bioconductor dependencies
    command: R -e 'BiocManager::install("{{ item }}", version = "3.8")'
    with_items:
      - "genefilter"
      - "GlobalAncova"
      - "impute"
      - "KEGGgraph"
      - "limma"
      - "pcaMethods"
      - "preprocessCore"
      - "Rgraphviz"
      - "siggenes"
      - "SSPA"
      - "sva"

  - name: Install metaboanalystr package
    command:
      R -e 'install.packages("devtools"); library(devtools); devtools::install_github("xia-lab/MetaboAnalystR")'
